name: larp-auction

contracts_folder: src

plugins:
  - name: vyper
  - name: alchemy
  - name: foundry
  - name: arbitrum
  - name: solidity
  - name: etherscan

vyper:
  version: 0.3.10

test:
  disconnect_providers_after: false
  number_of_accounts: 5

# this sets arbitrum:mainnet-fork:foundry as the default
default_ecosystem: arbitrum
arbitrum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry
  sepolia:
    default_provider: geth
  mainnet:
    default_provider: alchemy
ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry
  sepolia:
    default_provider: alchemy

# this configures foundry to use alchemy as the upstream provider
foundry:
  port: 8545
  fork:
    arbitrum:
      mainnet:
        upstream_provider: alchemy
        # block_number: 170140700
    ethereum:
      mainnet:
        upstream_provider: alchemy

geth:
  arbitrum:
    sepolia:
      uri: https://arb-sepolia.g.alchemy.com/v2/<API_KEY>
    mainnet:
      uri: https://arb-mainnet.g.alchemy.com/v2/<API_KEY>
